import type { Metadata } from "next"
import { Inter, Chivo } from "next/font/google"
import "./globals.css"
import Navbar from "./components/ui/navbar/navbar"

const chivo = Chivo({ subsets: ["latin"] })

export const metadata: Metadata = {
	title: "Mendoza Lash Beauty",
	description: "Generated by create next app",
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en" data-theme="bumblebee">
			<body className={chivo.className + " lg:mx-40 px-5 md:mx-10 mx-0"}>
				<Navbar />
				{children}
			</body>
		</html>
	)
}
